name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

env:
  app_name: RegexFileSearcher
  publish_folder: publish

jobs:
  build:
    name: ${{ matrix.config.name }} | Release
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: Windows,
            os: windows-latest,
            project: Wpf,
            runtime: win-x86,
            framework: net5.0-windows,
            is_single_file: "false"
          }
        - {
            name: Linux,
            os: ubuntu-latest,
            project: Gtk,
            runtime: linux-x64,
            framework: net5.0,
            is_single_file: "true"
          }
        - {
            name: macOS,
            os: macos-latest,
            project: Mac,
            runtime: osx-x64,
            framework: net5.0,
            is_single_file: "true"
          }

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
         
      # This cheap hack is needed because of a build environment "bug": https://github.com/actions/setup-dotnet/issues/155
      - name: Clean
        run: dotnet clean && dotnet nuget locals all --clear

      - name: Publish
        run: dotnet publish ${{ env.app_name }}/${{ env.app_name }}.${{ matrix.config.project }}/${{ env.app_name }}.${{ matrix.config.project }}.csproj --configuration Release --output ${{ env.publish_folder }} --self-contained true -p:PublishSingleFile=${{ matrix.config.is_single_file }} --runtime ${{ matrix.config.runtime }} --framework ${{ matrix.config.framework }}

      - name: Get the tag name
        id: get_tag_name
        if: (github.event_name == 'release' && github.event.action == 'published' && startsWith(github.ref, 'refs/tags/'))
        shell: bash
        run: echo "::set-output name=TAG_NAME::$(git describe --tags --abbrev=0)"

      - name: Create Package
        if: (github.event_name == 'release' && github.event.action == 'published' && startsWith(github.ref, 'refs/tags/'))
        shell: bash
        run: |
            filename=${{ env.app_name }}-${{ steps.get_tag_name.outputs.TAG_NAME }}-${{ matrix.config.runtime }}
            if [[ "${{ runner.os }}" == 'Windows' ]]; then
              7z a $filename.zip ./${{ env.publish_folder }}/*
            else
              zip --junk-paths $filename ./${{ env.publish_folder }}/*
            fi

      - uses: actions/upload-artifact@v2
        if: (github.event_name == 'release' && github.event.action == 'published' && startsWith(github.ref, 'refs/tags/'))
        with:
            name: ${{ matrix.config.runtime }} Release
            path: ${{ env.app_name }}-${{ steps.get_tag_name.outputs.TAG_NAME }}-${{ matrix.config.runtime }}.zip

      - uses: actions/upload-artifact@v2
        if: (github.event_name == 'push' || github.event_name == 'pull_request')
        with:
            name: ${{ matrix.config.runtime }} Release
            path: ${{ env.publish_folder }}

      - name: List Build Directory
        if: always()
        shell: bash
        run: |
          git status
          ls -lR ${{ env.publish_folder }}

  upload-packages:
    needs: build
    runs-on: ubuntu-latest
    if: (github.event_name == 'release' && github.event.action == 'published' && startsWith(github.ref, 'refs/tags/'))
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            runtime: win-x86
          }
        - {
            runtime: linux-x64
          }
        - {
            runtime: osx-x64
          }
    steps:
      - name: Get the tag name
        id: get_tag_name
        if: (github.event_name == 'release' && github.event.action == 'published' && startsWith(github.ref, 'refs/tags/'))
        shell: bash
        run: echo "::set-output name=TAG_NAME::$(git describe --tags --abbrev=0)"

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Download extension artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.config.runtime }} Release

      - name:  Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ env.app_name }}-${{ steps.get_tag_name.outputs.TAG_NAME }}-${{ matrix.config.runtime }}.zip
          asset_name: ${{ env.app_name }}-${{ steps.get_tag_name.outputs.TAG_NAME }}-${{ matrix.config.runtime }}.zip
          asset_content_type: application/zip
